# Generated by Django 4.1.7 on 2023-04-15 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('poem', 'Poem'), ('article', 'Article'), ('fanfiction', 'Fanfiction'), ('prose', 'Prose'), ('essay', 'Essay')], default='prose', max_length=30)),
                ('file', models.FileField(upload_to='')),
                ('roll_number', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
