# Generated by Django 4.1.7 on 2023-04-12 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("readerSection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="roll_number",
            field=models.ForeignKey(
                default="none",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
