# Generated by Django 4.1.7 on 2023-04-17 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("readerSection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("poem", "Poem"),
                            ("article", "Article"),
                            ("fanfiction", "Fanfiction"),
                            ("prose", "Prose"),
                            ("essay", "Essay"),
                        ],
                        default="prose",
                        max_length=30,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "roll_number",
                    models.ForeignKey(
                        default="none",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FileUpload",
        ),
    ]
