# Generated by Django 4.1.7 on 2023-05-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerSection', '0003_content_delete_contentupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='background',
            field=models.ImageField(default=None, upload_to='content'),
        ),
    ]
