# Generated by Django 4.1.7 on 2023-04-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="roll_number",
            field=models.CharField(default="none", max_length=9),
        ),
    ]
