# Generated by Django 4.1.7 on 2023-07-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='request_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
