# Generated by Django 4.1.7 on 2023-06-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_by', models.CharField(max_length=200)),
                ('puzzle_type', models.CharField(max_length=200)),
                ('puzzle', models.FileField(default=None, upload_to='puzzle')),
            ],
        ),
    ]
