# Generated by Django 4.1.7 on 2023-06-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_title',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
