# Generated by Django 4.1.7 on 2023-03-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('por', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('linkedin', models.URLField()),
                ('instagram', models.URLField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
