# Generated by Django 4.1.7 on 2023-05-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default=None, upload_to='team'),
        ),
    ]
