# Generated by Django 4.1.7 on 2023-04-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="image",
            field=models.ImageField(default=None, upload_to=""),
        ),
    ]
