# Generated by Django 4.1.7 on 2023-05-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='description',
            new_name='quote',
        ),
        migrations.AddField(
            model_name='team',
            name='div_id',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='mail',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
