# Generated by Django 4.1.7 on 2023-04-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_team_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="hierarchy",
            field=models.IntegerField(default=1),
        ),
    ]
